/*************************************************************************/
// Author        : Sherif Ashraf Khedr
// Project       : Stm32f103c6x_Drivers
// File          : EXTI.h
// Date          : Jan 16, 2024
// GitHub        : https://github.com/khedr05
/*************************************************************************/

#ifndef MCAL_INC_EXTI_H_
#define MCAL_INC_EXTI_H_

#include "stm32f103x6.h"
#include "GPIO.h"
#include "NVIC.h"


#define MEXTI_MASKED 	 0
#define MEXTI_UNMASKED   1

typedef enum
{
	MEXTI_LINE0 = 0,
	MEXTI_LINE1,
	MEXTI_LINE2,
	MEXTI_LINE3,
	MEXTI_LINE4,
	MEXTI_LINE5,
	MEXTI_LINE6,
	MEXTI_LINE7,
	MEXTI_LINE8,
	MEXTI_LINE9,
	MEXTI_LINE10,
	MEXTI_LINE11,
	MEXTI_LINE12,
	MEXTI_LINE13,
	MEXTI_LINE14,
	MEXTI_LINE15
}MEXTI_uddtLines_t;


typedef enum
{
	MEXTI_TRIGGER_FALLING = 0,
	MEXTI_TRIGGER_RISING,
	MEXTI_TRIGGER_BOTH
}MEXTI_uddtTrigger_t;


typedef struct
{
	MEXTI_uddtLines_t      uddtLine;
	GPIO_registerMap_t	   *uddtGpioPort;
	MGPIO_uddtPinNumber_t  uddtPinNumber;
	uint8				   u8IvtIRQNumber;
}MEXTI_uddtGpioPin_t;

typedef struct
{
	MEXTI_uddtGpioPin_t    uddtPinData;
	MEXTI_uddtTrigger_t    uddtTriggerControl;
	uint8				   u8IRQStatus;
	void(*IRQCallback)(void);
}MEXTI_uddtCfg_t;


//EXTI0
#define EXTI0PA0	(MEXTI_uddtGpioPin_t){MEXTI_LINE0, GPIOA, MGPIO_PIN0, MNVIC_EXTI0_IRQ}
#define EXTI0PB0	(MEXTI_uddtGpioPin_t){MEXTI_LINE0, GPIOB, MGPIO_PIN0, MNVIC_EXTI0_IRQ}
#define EXTI0PC0	(MEXTI_uddtGpioPin_t){MEXTI_LINE0, GPIOC, MGPIO_PIN0, MNVIC_EXTI0_IRQ}

//EXTI1
#define EXTI1PA1	(MEXTI_uddtGpioPin_t){MEXTI_LINE1, GPIOA, MGPIO_PIN1, MNVIC_EXTI1_IRQ}
#define EXTI1PB1	(MEXTI_uddtGpioPin_t){MEXTI_LINE1, GPIOB, MGPIO_PIN1, MNVIC_EXTI1_IRQ}
#define EXTI1PC1    (MEXTI_uddtGpioPin_t){MEXTI_LINE1, GPIOC, MGPIO_PIN1, MNVIC_EXTI1_IRQ}

//EXTI2
#define EXTI2PA2	(MEXTI_uddtGpioPin_t){MEXTI_LINE2, GPIOA, MGPIO_PIN2, MNVIC_EXTI2_IRQ}
#define EXTI2PB2	(MEXTI_uddtGpioPin_t){MEXTI_LINE2, GPIOB, MGPIO_PIN2, MNVIC_EXTI2_IRQ}
#define EXTI2PC2	(MEXTI_uddtGpioPin_t){MEXTI_LINE2, GPIOC, MGPIO_PIN2, MNVIC_EXTI2_IRQ}

//EXTI3
#define EXTI3PA3	(MEXTI_uddtGpioPin_t){MEXTI_LINE3, GPIOA, MGPIO_PIN3, MNVIC_EXTI3_IRQ}
#define EXTI3PB3	(MEXTI_uddtGpioPin_t){MEXTI_LINE3, GPIOB, MGPIO_PIN3, MNVIC_EXTI3_IRQ}
#define EXTI3PC3	(MEXTI_uddtGpioPin_t){MEXTI_LINE3, GPIOC, MGPIO_PIN3, MNVIC_EXTI3_IRQ}

//EXTI4
#define EXTI4PA4	(MEXTI_uddtGpioPin_t){MEXTI_LINE4, GPIOA, MGPIO_PIN4, MNVIC_EXTI4_IRQ}
#define EXTI4PB4	(MEXTI_uddtGpioPin_t){MEXTI_LINE4, GPIOB, MGPIO_PIN4, MNVIC_EXTI4_IRQ}
#define EXTI4PC4	(MEXTI_uddtGpioPin_t){MEXTI_LINE4, GPIOC, MGPIO_PIN4, MNVIC_EXTI4_IRQ}

//EXTI5
#define EXTI5PA5	(MEXTI_uddtGpioPin_t){MEXTI_LINE5, GPIOA, MGPIO_PIN5, MNVIC_EXTI5_IRQ}
#define EXTI5PB5	(MEXTI_uddtGpioPin_t){MEXTI_LINE5, GPIOB, MGPIO_PIN5, MNVIC_EXTI5_IRQ}
#define EXTI5PC5	(MEXTI_uddtGpioPin_t){MEXTI_LINE5, GPIOC, MGPIO_PIN5, MNVIC_EXTI5_IRQ}

//EXTI6
#define EXTI6PA6	(MEXTI_uddtGpioPin_t){MEXTI_LINE6, GPIOA, MGPIO_PIN6, MNVIC_EXTI9_5_IRQ}
#define EXTI6PB6	(MEXTI_uddtGpioPin_t){MEXTI_LINE6, GPIOB, MGPIO_PIN6, MNVIC_EXTI9_5_IRQ}
#define EXTI6PC6	(MEXTI_uddtGpioPin_t){MEXTI_LINE6, GPIOC, MGPIO_PIN6, MNVIC_EXTI9_5_IRQ}

//EXTI7
#define EXTI7PA7	(MEXTI_uddtGpioPin_t){MEXTI_LINE7, GPIOA, MGPIO_PIN7, MNVIC_EXTI9_5_IRQ}
#define EXTI7PB7	(MEXTI_uddtGpioPin_t){MEXTI_LINE7, GPIOB, MGPIO_PIN7, MNVIC_EXTI9_5_IRQ}
#define EXTI7PC7	(MEXTI_uddtGpioPin_t){MEXTI_LINE7, GPIOC, MGPIO_PIN7, MNVIC_EXTI9_5_IRQ}

//EXTI8
#define EXTI8PA8	(MEXTI_uddtGpioPin_t){MEXTI_LINE8, GPIOA, MGPIO_PIN8, MNVIC_EXTI9_5_IRQ}
#define EXTI8PB8	(MEXTI_uddtGpioPin_t){MEXTI_LINE8, GPIOB, MGPIO_PIN8, MNVIC_EXTI9_5_IRQ}
#define EXTI8PC8	(MEXTI_uddtGpioPin_t){MEXTI_LINE8, GPIOC, MGPIO_PIN8, MNVIC_EXTI9_5_IRQ}

//EXTI9
#define EXTI9PA9	(MEXTI_uddtGpioPin_t){MEXTI_LINE9, GPIOA, MGPIO_PIN9, MNVIC_EXTI9_5_IRQ}
#define EXTI9PB9	(MEXTI_uddtGpioPin_t){MEXTI_LINE9, GPIOB, MGPIO_PIN9, MNVIC_EXTI9_5_IRQ}
#define EXTI9PC9	(MEXTI_uddtGpioPin_t){MEXTI_LINE9, GPIOC, MGPIO_PIN9, MNVIC_EXTI9_5_IRQ}

//EXTI10
#define EXTI10PA10	(MEXTI_uddtGpioPin_t){MEXTI_LINE10, GPIOA, MGPIO_PIN10, MNVIC_EXTI15_10_IRQ}
#define EXTI10PB10	(MEXTI_uddtGpioPin_t){MEXTI_LINE10, GPIOB, MGPIO_PIN10, MNVIC_EXTI15_10_IRQ}
#define EXTI10PC10	(MEXTI_uddtGpioPin_t){MEXTI_LINE10, GPIOC, MGPIO_PIN10, MNVIC_EXTI15_10_IRQ}

//EXTI11
#define EXTI11PA11	(MEXTI_uddtGpioPin_t){MEXTI_LINE11, GPIOA, MGPIO_PIN11, MNVIC_EXTI15_10_IRQ}
#define EXTI11PB11  (MEXTI_uddtGpioPin_t){MEXTI_LINE11, GPIOB, MGPIO_PIN11, MNVIC_EXTI15_10_IRQ}
#define EXTI11PC11	(MEXTI_uddtGpioPin_t){MEXTI_LINE11, GPIOC, MGPIO_PIN11, MNVIC_EXTI15_10_IRQ}

//EXTI12
#define EXTI12PA12	(MEXTI_uddtGpioPin_t){MEXTI_LINE12, GPIOA, MGPIO_PIN12, MNVIC_EXTI15_10_IRQ}
#define EXTI12PB12	(MEXTI_uddtGpioPin_t){MEXTI_LINE12, GPIOB, MGPIO_PIN12, MNVIC_EXTI15_10_IRQ}
#define EXTI12PC12	(MEXTI_uddtGpioPin_t){MEXTI_LINE12, GPIOC, MGPIO_PIN12, MNVIC_EXTI15_10_IRQ}

//EXTI13
#define EXTI13PA13	(MEXTI_uddtGpioPin_t){MEXTI_LINE13, GPIOA, MGPIO_PIN13, MNVIC_EXTI15_10_IRQ}
#define EXTI13PB13	(MEXTI_uddtGpioPin_t){MEXTI_LINE13, GPIOB, MGPIO_PIN13, MNVIC_EXTI15_10_IRQ}
#define EXTI13PC13	(MEXTI_uddtGpioPin_t){MEXTI_LINE13, GPIOC, MGPIO_PIN13, MNVIC_EXTI15_10_IRQ}

//EXTI14
#define EXTI14PA14	(MEXTI_uddtGpioPin_t){MEXTI_LINE14, GPIOA, MGPIO_PIN14, MNVIC_EXTI15_10_IRQ}
#define EXTI14PB14	(MEXTI_uddtGpioPin_t){MEXTI_LINE14, GPIOB, MGPIO_PIN14, MNVIC_EXTI15_10_IRQ}
#define EXTI14PC14	(MEXTI_uddtGpioPin_t){MEXTI_LINE14, GPIOC, MGPIO_PIN14, MNVIC_EXTI15_10_IRQ}

//EXTI15
#define EXTI15PA15	(MEXTI_uddtGpioPin_t){MEXTI_LINE15, GPIOA, MGPIO_PIN15, MNVIC_EXTI15_10_IRQ}
#define EXTI15PB15	(MEXTI_uddtGpioPin_t){MEXTI_LINE15, GPIOB, MGPIO_PIN15, MNVIC_EXTI15_10_IRQ}
#define EXTI15PC15	(MEXTI_uddtGpioPin_t){MEXTI_LINE15, GPIOC, MGPIO_PIN15, MNVIC_EXTI15_10_IRQ}


COMMON_uddtApiState_t  MEXTI_uddtInit(MEXTI_uddtCfg_t *EXTIx);
COMMON_uddtApiState_t  MEXTI_uddtSwInterrupt(MEXTI_uddtCfg_t *EXTIx);
COMMON_uddtApiState_t  MEXTI_uddtMaskLine(MEXTI_uddtCfg_t *EXTIx);
COMMON_uddtApiState_t  MEXTI_uddtUnmaskLine(MEXTI_uddtCfg_t *EXTIx);
COMMON_uddtApiState_t  MEXTI_uddtReset(void);
COMMON_uddtApiState_t  MEXTI_uddtUpdate(MEXTI_uddtCfg_t *EXTIx);

#endif /* MCAL_INC_EXTI_H_ */
